### ISSUE TITLE
MD5 hashing hangs indefinitely when reading any file with special characters

### ISSUE THREAD

**Issue by 0xjmp** [firmadyne/extractor#7]
Hello, thank you for maintaining firmadyne!

I am running firmadyne inside a fresh VM using Ubuntu jammy 22.04.1.

While extracting a firmware (that I unfortunately cannot share here), I found that reading a special character file (e.g. `/dev/console`) causes the `io_md5` function to hang indefinitely.

I am able to workaround the issue by using this patch:
```
diff --git a/extractor.py b/extractor.py
index d5f77ac..e661cbc 100755      
--- a/extractor.py                                                                                                     
+++ b/extractor.py                                         
@@ -111,12 +111,16 @@ class Extractor(object):
         blocksize = 65536
         hasher = hashlib.md5()             
                                                           
-        with open(target, 'rb') as ifp:                   
-            buf = ifp.read(blocksize)
-            while buf:                                    
-                hasher.update(buf)           
+        file_size = os.path.getsize(target)
+        if file_size == 0:                                
+            hasher.update(target)
+        else:                                             
+            with open(target, 'rb') as ifp:                                                                           
                 buf = ifp.read(blocksize)
-            return hasher.hexdigest()
+                while buf:
+                    hasher.update(buf)                    
+                    buf = ifp.read(blocksize)                                                                         
+        return hasher.hexdigest()
                     
     @staticmethod    
     def io_rm(target): 
```
Basically, the logic is modified to hash `file_size == 0` files by their file name (instead of the typical approach of hashing file contents).

Please let me know if you would like this to be made into a PR, and I'd be happy to do so 🚀

**Comment by ddcc** [comment]
I'd be happy to take a PR, but I think the right approach would be to use the filename only if the file is special; e.g. call `os.stat()` and check that it's not a regular file (`!stat.S_ISREG(mode)`). There's no point recursing on zero-size files because they won't extract to anything, so it's ok that all zero-size files will share the same checksum.

**Comment by 0xjmp** [comment]
Agreed. Opened https://github.com/firmadyne/extractor/pull/8/files

**Comment by ddcc** [comment]
Handled in #8 , thanks!
